name: 2-Security-Scan-SAST-SCA

on:
  workflow_dispatch:
  schedule:
    # Runs "Every Sunday" (see https://crontab.guru)
    - cron: '5 8 * * Sun'

jobs:
  Veracode_SAST_SCA_Scan:

    runs-on: ubuntu-latest
    container: 
      image: veracode/api-wrapper-java:latest
      options: --user root
    steps:
        
# Security Scan Mainline Branch / SAST and SCA Sanbox Scan
      
    - name: Download Checkout-Build-Artifact Workflow Artifact
      uses: qiwi-forks/action-download-artifact@v2
      with: 
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: 1-Checkout-Build-Artifact.yml
        name: VeraDemoDotNetCoreAppArtifact
        skip_unpack: true
      continue-on-error: false
    
    - name: List folder contents for visual to confirm artifact file exists
      run: |
        ls -la
    
    - name: Submit Security Scan SAST SCA
      run: |
        java -jar /opt/veracode/api-wrapper.jar -vid "${{secrets.VERACODE_API_ID}}" -vkey "${{secrets.VERACODE_API_KEY}}" -action UploadAndScan -createprofile false -appname VeraDemo-DotNetCore-GitHub -version "${{ github.run_id }}" -filepath VeraDemoDotNetCoreAppArtifact.zip
