name: 3-Build and Publish Docker Image

on:
  workflow_dispatch:
  schedule:
    # Runs "Every Sunday" (see https://crontab.guru)
    - cron: '15 8 * * Sun'

jobs:

  Dockerize-Publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # Dockerize-Publish
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Pull Ubuntu MSSQL Docker Image Dependency
      run: docker pull mcr.microsoft.com/mssql/server:2017-CU24-ubuntu-16.04      

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v3.2.0
      with:
        context: .
        push: true
        tags: veracodedemolabs/verademo-dotnetcore-github:latest
